version: '3'

networks:
  tailscale_proxy_example:
    external: false

volumes:
  tailscale-whoami-state:

services:

  tailscale-whoami-proxy:
#    image: hollie/tailscale-caddy-proxy:buildx-latest
    build:
      context: ./image
    volumes:
      - tailscale-whoami-state:/var/lib/tailscale # Persist the tailscale state directory
    environment:
      - TS_HOSTNAME=tstest		# Hostname you want this instance to have on the tailscale network
      - TS_TAILNET=hedgehog-decibel     # Fill in your tailnet name here without the .ts.net suffix!
      - CADDY_TARGET=whoami:80		# Target service and port
    restart: on-failure
    init: true
    networks:
     - tailscale_proxy_example

  whoami:
    image: traefik/whoami
    networks:
     - tailscale_proxy_example
